FROM archlinux:base-devel

RUN mkdir -p /etc/pacman.d/hooks \
	&& ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook

RUN pacman --noconfirm -Syu \
	&& pacman --needed --noconfirm -S \
		arp-scan \
		python \
		parted \
		dosfstools \
		rsync \
	&& (pacman --noconfirm -Sc || true)

RUN mkdir /tools
COPY install-binfmt /tools/
COPY docker-extract /tools/
