FROM archlinux/archlinux:base-devel-20210205.0.15146

RUN mkdir -p /etc/pacman.d/hooks \
	&& ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook

RUN pacman --noconfirm -Sy \
	&& pacman --needed --noconfirm -S \
		arp-scan \
		python \
		parted \
		dosfstools \
		rsync \
	&& (pacman --noconfirm -Sc || true) \
	&& rm -rf /var/cache/pacman/pkg/*

RUN mkdir /tools
COPY install-binfmt /tools/
COPY docker-extract /tools/
