#!/bin/sh
set -e
set -x

SAY="/tools/say"
DIE="/tools/die"

QEMU_RUNNER_STATIC_PLACE="$1"
QEMU_RUNNER_ARCH="$2"

[ `whoami` == "root" ] || $DIE "===== Run as root plz ====="
[ -n "$QEMU_RUNNER_STATIC_PLACE" ] || $DIE "===== Empty QEMU_RUNNER_STATIC_PLACE arg ====="
[ -n "$QEMU_RUNNER_ARCH" ] || $DIE "===== Empty QEMU_RUNNER_ARCH arg ====="

BINFMT_DIR="/proc/sys/fs/binfmt_misc"
BINFMT_ARM="$BINFMT_DIR/$QEMU_RUNNER_ARCH"

$SAY "===== Configuring ARM-binfmt ($QEMU_RUNNER_ARCH) ====="
mount binfmt_misc -t binfmt_misc "$BINFMT_DIR"
if [ -e "$BINFMT_ARM" ]; then
	real=`grep interpreter "$BINFMT_ARM" | awk '{print $2}'`
	if [ "$QEMU_RUNNER_STATIC_PLACE" != "$real" ]; then
		$DIE -e " ARM-binfmt ($QEMU_RUNNER_ARCH) is enabled but path is inconsistent\n"\
			"  > $BINFMT_ARM: $real\n"\
			"  > expected: $QEMU_RUNNER_STATIC_PLACE\n"\
			" Run \"echo -1 > $BINFMT_ARM\" to disable ARM globally (include the host system)"
	fi
else
	$SAY -e "===== Enabling ARM-binfmt ($QEMU_RUNNER_ARCH) ====="
	# https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh
	if [ "$QEMU_RUNNER_ARCH" == "arm" ]; then
		magic="\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	elif [ "$QEMU_RUNNER_ARCH" == "aarch64" ]; then
		magic="\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	else
		$DIE " Unsupported QEMU arch: $QEMU_RUNNER_ARCH"
	fi
	echo ":$QEMU_RUNNER_ARCH:M::$magic:$mask:$QEMU_RUNNER_STATIC_PLACE:" > "$BINFMT_DIR/register"
fi
$SAY "===== ARM-binfmt is ready ($QEMU_RUNNER_ARCH) ====="
