#!/bin/sh
set -e
set -x

SAY="/tools/say"
DIE="/tools/die"

QEMU_STATIC_GUEST_PATH="$1"
QEMU_GUEST_ARCH="$2"

[ `whoami` == "root" ] || $DIE "===== Run as root plz ====="
[ -n "$QEMU_STATIC_GUEST_PATH" ] || $DIE "===== Empty QEMU_STATIC_GUEST_PATH arg ====="
[ -n "$QEMU_GUEST_ARCH" ] || $DIE "===== Empty QEMU_GUEST_ARCH arg ====="

BINFMT_DIR="/proc/sys/fs/binfmt_misc"
BINFMT_ARM="$BINFMT_DIR/$QEMU_GUEST_ARCH"

$SAY "===== Configuring ARM-binfmt ($QEMU_GUEST_ARCH) ====="
mount binfmt_misc -t binfmt_misc "$BINFMT_DIR"
if [ -e "$BINFMT_ARM" ]; then
	real=`grep interpreter "$BINFMT_ARM" | awk '{print $2}'`
	if [ "$QEMU_STATIC_GUEST_PATH" != "$real" ]; then
		$DIE -e " ARM-binfmt ($QEMU_GUEST_ARCH) is enabled but path is inconsistent\n"\
			"  > $BINFMT_ARM: $real\n"\
			"  > expected: $QEMU_STATIC_GUEST_PATH\n"\
			" Run \"echo -1 > $BINFMT_ARM\" to disable ARM globally (include the host system)"
	fi
else
	$SAY -e "===== Enabling ARM-binfmt ($QEMU_GUEST_ARCH) ====="
	# https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh
	if [ "$QEMU_GUEST_ARCH" == "arm" ]; then
		magic="\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	elif [ "$QEMU_GUEST_ARCH" == "aarch64" ]; then
		magic="\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	else
		$DIE " Unsupported QEMU arch: $QEMU_GUEST_ARCH"
	fi
	echo ":$QEMU_GUEST_ARCH:M::$magic:$mask:$QEMU_STATIC_GUEST_PATH:" > "$BINFMT_DIR/register"
fi
$SAY "===== ARM-binfmt is ready ($QEMU_GUEST_ARCH) ====="
