COPY stages/boot /tmp/boot
RUN [ ! -d /tmp/boot/boot-$BOARD-$ARCH ] || cp -a /tmp/boot/boot-$BOARD-$ARCH/* /boot/
RUN [ ! -f /boot/mkscr ] || ( pacman --noconfirm --needed -S uboot-tools && cd /boot && /boot/mkscr )
RUN ls -la /boot && rm -rf /tmp/boot
