#!/bin/sh
if [ `whoami` != root ]; then
	echo "Only root can do that"
	exit 1
fi
pacman --noconfirm -Syu && pacman --noconfirm --needed -S $@
retval=$?
pacman --noconfirm -Sc
rm -rf /var/cache/pacman/pkg/*
exit $retval
