FROM mdevaev/archlinux

ENV SITE_FS /root/site-fs
ENV FS      /root/fs


# ===== Builder =====
RUN pacman --noconfirm -Syy \
	&& pacman --noconfirm -S pacman \
	&& pacman-db-upgrade \
	&& pacman --noconfirm -Syu \
	&& pacman --noconfirm -S \
		binutils \
		arch-install-scripts \
		rsync \
	&& pacman --noconfirm -Sc


# ===== RPI filesystem =====
ENV RPI_MIRROR_URL http://mirror.yandex.ru/archlinux-arm
ENV RPI_ROOTFS_URL http://mirror.yandex.ru/archlinux-arm/os/ArchLinuxARM-%%PLATFORM%%-latest.tar.gz

RUN mkdir $SITE_FS \
	&& wget $RPI_ROOTFS_URL -O $SITE_FS.tar.gz \
	&& tar -xzf $SITE_FS.tar.gz -C $SITE_FS \
	&& rm -f $SITE_FS.tar.gz
RUN echo "Server = $RPI_MIRROR_URL/\$arch/\$repo" > $SITE_FS/etc/pacman.d/mirrorlist

ENV QEMU_USER_STATIC_BASE_URL http://mirror.yandex.ru/debian/pool/main/q/qemu
ENV QEMU_ARM_STATIC /usr/bin/qemu-arm-static

RUN mkdir /root/qemu \
	&& wget -L $QEMU_USER_STATIC_BASE_URL/`curl -s $QEMU_USER_STATIC_BASE_URL/ \
			| grep qemu-user-static \
			| grep _amd64.deb \
			| sort -n \
			| tail -n 1 \
			| sed -n 's/.*href="\([^"]*\).*/\1/p'` \
		-O /root/qemu/qemu-user-static.deb \
	&& cd /root/qemu \
	&& ar vx qemu-user-static.deb \
	&& tar -xJf data.tar.xz \
	&& cp usr/bin/qemu-arm-static $SITE_FS/$QEMU_ARM_STATIC \
	&& cd - \
	&& rm -rf /root/qemu


# ===== Scripts for building =====
ADD build-rpi.sh /usr/local/bin/build-rpi
ADD scripts /root/scripts

WORKDIR /root
CMD bash
