FROM archlinux/base

RUN pacman --noconfirm -Syu \
	&& pacman --needed --noconfirm -S \
		base-devel \
		arp-scan \
		python \
		parted \
		dosfstools \
		rsync \
	&& (pacman --noconfirm -Sc || true)

COPY say /usr/local/bin/
COPY die /usr/local/bin/
COPY install-binfmt /usr/local/bin/
COPY docker-extract /usr/local/bin/
