#!/bin/sh
set -e
set -x

[ `whoami` == "root" ] || die "===== Run as root plz ====="
[ -n "$1" ] || die "===== Empty QEMU_RUNNER_STATIC_PLACE arg ====="
[ -n "$2" ] || die "===== Empty QEMU_RUNNER_ARCH arg ====="

BINFMT_DIR="/proc/sys/fs/binfmt_misc"
BINFMT_ARM="$BINFMT_DIR/$2"

say "===== Configuring ARM-binfmt ($2) ====="
mount binfmt_misc -t binfmt_misc "$BINFMT_DIR"
if [ -e "$BINFMT_ARM" ]; then
	REAL_QEMU_RUNNER_STATIC=`grep interpreter "$BINFMT_ARM" | awk '{print $2}'`
	if [ "$1" != "$REAL_QEMU_RUNNER_STATIC" ]; then
		die -e " ARM-binfmt ($2) is enabled but path is inconsistent\n"\
			"  > $BINFMT_ARM: $REAL_QEMU_RUNNER_STATIC\n"\
			"  > expected: $1\n"\
			" Run \"echo -1 > $BINFMT_ARM\" to disable ARM globally (include host system)"
	fi
else
	say -e "===== Enabling ARM-binfmt ($2) ====="
	# https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh
	if [ "$2" == "arm" ]; then
		magic="\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	elif [ "$2" == "aarch64" ]; then
		magic="\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00"
		mask="\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff"
	else
		die " Unsupported QEMU arch: $2"
	fi
	echo ":$2:M::$magic:$mask:$1:" > "$BINFMT_DIR/register"
fi
say "===== ARM-binfmt is ready ($2) ====="
