#!/bin/sh
set -e
set -x

[ `whoami` == "root" ] || die "===== Run as root plz ====="
[ -n "$1" ] || die "===== Empty QEMU_ARM_STATIC_PLACE arg ====="

BINFMT_DIR="/proc/sys/fs/binfmt_misc"
BINFMT_ARM="$BINFMT_DIR/arm"

say "===== Configuring ARM-binfmt ====="
mount binfmt_misc -t binfmt_misc "$BINFMT_DIR"
if [ -e "$BINFMT_ARM" ]; then
	REAL_QEMU_ARM_STATIC=`grep interpreter "$BINFMT_ARM" | awk '{print $2}'`
	if [ "$1" != "$REAL_QEMU_ARM_STATIC" ]; then
		die -e " ARM-binfmt is enabled but path is inconsistent\n"\
			"  > $BINFMT_ARM: $REAL_QEMU_ARM_STATIC\n"\
			"  > expected: $1\n"\
			" Run \"echo -1 > $BINFMT_ARM\" to disable ARM globally (include host system)"
	fi
else
	say -e "===== Enabling ARM-binfmt ====="
	echo ":arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:$1:" > "$BINFMT_DIR/register"
fi
say "===== ARM-binfmt is ready ====="
